import React, {Component} from 'react';
require('../style/Body.scss');

export default class Body extends Component {
  render() {
    return (
      <div className='body'>
        <h1>Lorem Ipsum</h1>
        <h2>"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."</h2>
        <h2>"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..."</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent rhoncus nisi nec finibus tristique. Nunc feugiat id enim at sollicitudin. Curabitur lacus velit, vehicula faucibus consequat ut, imperdiet commodo urna. Nunc molestie metus at pulvinar convallis. Fusce auctor non arcu quis eleifend. Integer fringilla, mauris dictum consequat facilisis, nulla elit sollicitudin risus, vitae aliquam orci lorem nec elit. Praesent tincidunt sapien in tristique porta. Morbi in metus molestie, tincidunt lorem quis, vulputate nulla. Suspendisse blandit diam quam, vitae iaculis metus iaculis vitae. Suspendisse lorem nulla, eleifend in ipsum non, convallis rutrum metus. Quisque lacinia hendrerit sapien, a accumsan quam varius non. Proin metus tortor, sagittis sit amet mi vel, tempus volutpat tortor. Quisque ut feugiat odio, et luctus nisi. Nam pulvinar felis ut quam fringilla cursus eget ut tellus. Proin rhoncus diam sem, a bibendum dui mattis ut. Integer id quam urna.</p>
        <p>Sed dapibus est mi, nec ornare enim facilisis ut. Donec convallis leo ac mauris sagittis aliquam. In tellus massa, condimentum quis dolor a, congue condimentum libero. Nulla facilisi. Aliquam commodo massa laoreet, iaculis orci a, tempus magna. Nam quis massa vitae orci tempus vestibulum nec a sapien. Mauris vel orci imperdiet, dapibus magna sed, commodo leo. Aliquam erat volutpat. Ut vulputate consequat finibus.</p>
        <p>Suspendisse potenti. Proin malesuada sagittis rutrum. Fusce hendrerit sapien tellus, quis mollis mauris egestas nec. Praesent efficitur pulvinar justo, eget tristique tellus condimentum in. Nulla pellentesque egestas nisi sit amet ultrices. Suspendisse rhoncus sagittis eros, sit amet faucibus risus tempus et. Nullam vestibulum augue neque, sed scelerisque elit porttitor in. Sed porta lobortis metus nec euismod. Donec vehicula urna eget interdum egestas. Suspendisse iaculis tortor sit amet finibus ullamcorper. Mauris consectetur nunc non nibh vehicula sagittis. In hac habitasse platea dictumst.</p>
        <p>Donec euismod tortor eget justo ultricies interdum. Duis tempor aliquet felis, id ornare arcu malesuada non. Morbi non congue diam, non suscipit lacus. Nam aliquam sed purus sed blandit. Donec suscipit pellentesque tortor. Aliquam eu sodales velit. Quisque fermentum scelerisque dolor. Praesent cursus neque velit, in molestie diam commodo ac. Donec iaculis ex vitae fermentum finibus. Proin dapibus suscipit euismod. Cras blandit facilisis mi, gravida tincidunt ante consectetur sit amet. Pellentesque lacus dui, eleifend in porttitor sed, posuere in urna. In at augue lacinia felis mollis ullamcorper at vitae enim. Suspendisse at odio vel ligula tincidunt varius.</p>
        <p>Phasellus vel risus tortor. Donec suscipit, nibh ac varius faucibus, dui elit suscipit felis, et mattis ante velit sit amet ligula. Praesent sed tristique erat, mattis varius nunc. Aliquam ut purus gravida, pellentesque neque sit amet, ullamcorper ante. Nam rutrum elit at sem euismod condimentum. In venenatis felis arcu. Quisque lacinia euismod mattis. Ut at accumsan urna, vel molestie risus. Sed euismod odio quis volutpat finibus. Suspendisse diam lacus, semper non dapibus et, luctus quis velit. Pellentesque ac semper ex. Ut rutrum dictum finibus. Sed ultrices nisl nec nulla sagittis vestibulum. In vulputate ex vitae ex fermentum sagittis sed ultricies elit. Donec dictum volutpat ullamcorper.</p>
        <p>Duis lectus sapien, tincidunt id sollicitudin vitae, convallis eu magna. In eget metus commodo nulla semper semper eu at augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In dignissim tempus tellus faucibus commodo. Vestibulum dignissim at risus at venenatis. Nam metus odio, tristique in pharetra gravida, commodo eu lectus. Quisque porta tellus nec mauris vehicula malesuada. Sed a tincidunt odio, non euismod elit. Vestibulum tempus lectus vel dui maximus facilisis. Mauris eget augue magna. Suspendisse condimentum nisl et bibendum aliquet. Suspendisse potenti. Donec congue, mi at commodo aliquet, nibh mauris consectetur neque, sit amet facilisis augue lacus eget quam. Aliquam sagittis orci sit amet mi fringilla pharetra quis at mi. Integer aliquet arcu et placerat placerat.</p>
        <p>Vivamus dapibus lectus quis ligula euismod, eu ultricies lectus fringilla. Fusce posuere ante lacus, id commodo odio eleifend eu. Nam bibendum ante ut rutrum ultricies. Fusce quis leo nulla. Maecenas at metus eu sapien feugiat pharetra. Suspendisse non iaculis purus. Aliquam feugiat quis neque nec pellentesque. Nulla congue, ligula at iaculis malesuada, nunc sapien placerat purus, at ultrices ipsum massa ac purus. Mauris sit amet turpis eget magna ornare consequat.</p>
        <p>Aliquam erat volutpat. Curabitur mattis lobortis nisi. Quisque convallis erat ex, varius aliquet quam cursus non. Sed suscipit pharetra bibendum. Phasellus dui odio, placerat eget cursus ut, fermentum id leo. In eget augue velit. Proin libero purus, feugiat in lectus tempor, varius posuere sem. Quisque dapibus nulla ut tortor faucibus pretium. Integer id accumsan dolor. Aenean id consectetur est. Etiam nec leo nisi. Nam sem tellus, laoreet vel odio in, dignissim ultricies nibh. Suspendisse dignissim orci magna, nec condimentum dui commodo id. Aenean fermentum pellentesque facilisis. Nulla facilisi.</p>
        <p>Pellentesque convallis accumsan leo non interdum. Fusce convallis ut elit nec scelerisque. Maecenas scelerisque tempor convallis. Fusce vehicula orci est, nec luctus risus vehicula non. Proin purus ipsum, ullamcorper et fermentum ac, placerat sed tortor. Phasellus at ex nisi. Suspendisse quis dignissim elit, nec vestibulum mauris. Donec tristique tempus dolor id suscipit. Ut venenatis erat massa, feugiat lacinia purus pharetra id. Nam feugiat ornare pharetra. Nullam lacinia leo ut ligula ullamcorper molestie. Proin egestas mattis lectus vitae mollis. Vestibulum nec porttitor ex.</p>
        <p>Sed id turpis gravida, varius diam eu, fermentum nibh. Morbi scelerisque mauris ut purus laoreet rutrum. Fusce malesuada justo ut elit facilisis facilisis. Curabitur congue, nisl vel dictum tempus, libero felis gravida elit, vel varius est ex quis ante. Maecenas rutrum nibh ipsum, consequat tempus lorem convallis eu. Aenean sollicitudin eget dolor sed ultricies. Ut rhoncus, libero sed laoreet placerat, sapien nunc pretium felis, ut rhoncus diam libero non lacus.</p>
        <p>Morbi vitae auctor urna. Vivamus id orci eget velit laoreet consequat. Integer lacinia euismod augue eu hendrerit. Nulla egestas vitae magna in molestie. Vivamus interdum urna et viverra porta. Suspendisse blandit neque ac ipsum porta sodales. Praesent semper tincidunt sollicitudin. Vivamus laoreet eleifend venenatis. Duis massa magna, ultricies at placerat in, eleifend sed orci. In leo nisi, congue eget consectetur sit amet, fermentum in libero.</p>
        <p>Nam quis ipsum scelerisque, ornare lacus a, lobortis urna. Curabitur sit amet augue justo. Nulla eu odio a ante hendrerit euismod eu at lorem. Nunc dictum erat tempor aliquet imperdiet. Vestibulum euismod vulputate ante, ac ultricies elit. In hac habitasse platea dictumst. Mauris vel erat et ipsum molestie dapibus id nec eros. In convallis erat at augue eleifend scelerisque. Donec aliquam tortor in fringilla scelerisque. Pellentesque ex risus, porta sit amet aliquam non, rutrum eu mauris. Praesent tellus felis, dictum quis luctus ut, dictum a ante. Integer lacinia nisl sem, in finibus urna vehicula ac. Nullam eget risus dolor.</p>
        <p>Fusce dolor odio, posuere sit amet gravida ut, consequat consectetur tortor. Nunc sed nisl ipsum. Donec quis nibh id nulla bibendum tincidunt aliquam sed mauris. Nulla ultrices lectus quis ex mollis condimentum. Nam eget nulla vehicula, aliquet velit sit amet, sagittis tellus. Maecenas condimentum neque leo, nec placerat ligula congue ac. Vivamus sodales quam tortor, at tincidunt arcu lacinia vel. Integer vehicula fringilla mauris, id placerat metus gravida ac. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc vestibulum luctus mi, sit amet sodales elit mollis ut. Phasellus dictum aliquam sem, et sagittis dui posuere sit amet. Proin suscipit porttitor condimentum.</p>
        <p>Sed iaculis nunc mi, sit amet varius justo dictum nec. Ut sollicitudin ornare accumsan. Etiam cursus nibh sit amet metus viverra, ac varius nulla ullamcorper. Fusce at diam neque. Nunc ornare non nibh iaculis rhoncus. Pellentesque eu cursus quam. Nullam at metus egestas libero aliquet mattis sit amet non ante. Praesent erat diam, semper vitae lectus vel, posuere ullamcorper ipsum. Donec id nisi vitae quam vehicula lobortis. In a nibh in nibh rhoncus pellentesque in ac leo. Morbi ac finibus velit. Praesent et fringilla magna. Mauris in ornare tortor, eu pretium nisl. Nulla augue mauris, consequat nec congue ac, condimentum ac quam. Vestibulum vitae rhoncus turpis. Morbi blandit auctor tristique.</p>
        <p>Quisque sagittis vitae purus eget euismod. Donec rhoncus purus at est maximus, non imperdiet ante scelerisque. Duis at viverra metus. Phasellus sit amet fermentum enim. In hac habitasse platea dictumst. Vestibulum vel sodales erat, at tristique nisl. Cras turpis tortor, facilisis non porta vel, molestie non arcu. Donec posuere, justo at viverra aliquet, lacus justo egestas odio, a rutrum sapien diam quis odio. Etiam dapibus vel sapien id euismod. Vivamus ac magna vitae velit lacinia porta.</p>
      </div>
    )
  }
}
